name: Test on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm i -g pnpm && pnpm i

      - name: Set Environment Variables
        run: |
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "DATABASE_URI=postgresql://postgres:secret@localhost:5432/postgres" >> $GITHUB_ENV
  

      - name: Run Tests
        run: pnpm test
